/**
 * @author HaganWu
 * @description types
 * @fileName types.js
 * @data 2021/10/25 14:42
 */
export default {
    //导航更换主题
    THEME_CHANGE: "THEME_CHANGE",
    THEME_INIT: "THEME_INIT",
    SHOW_THEME_VIEW: "SHOW_THEME_VIEW",
    //最热页面
    POPULAR_REFRESH: "POPULAR_REFRESH",
    POPULAR_REFRESH_FAIL: "POPULAR_REFRESH_FAIL",
    POPULAR_REFRESH_SUCCESS: "POPULAR_REFRESH_SUCCESS",
    POPULAR_LOAD_MORE_SUCCESS: "POPULAR_LOAD_MORE_SUCCESS",
    POPULAR_LOAD_MORE_FAIL: "POPULAR_LOAD_MORE_FAIL",
    PLUSH_POPULAR_FAVORITE_STATE: "PLUSH_POPULAR_FAVORITE_STATE",
    //趋势页面
    TRENDING_REFRESH: "TRENDING_REFRESH",
    TRENDING_REFRESH_FAIL: "TRENDING_REFRESH_FAIL",
    TRENDING_REFRESH_SUCCESS: "TRENDING_REFRESH_SUCCESS",
    TRENDING_LOAD_MORE_SUCCESS: "TRENDING_LOAD_MORE_SUCCESS",
    TRENDING_LOAD_MORE_FAIL: "TRENDING_LOAD_MORE_FAIL",
    PLUSH_TRENDING_FAVORITE_STATE: "PLUSH_TRENDING_FAVORITE_STATE",
    //收藏页面
    FAVORITE_LOAD_DATA: "FAVORITE_LOAD_DATA",
    FAVORITE_LOAD_SUCCESS: "FAVORITE_LOAD_SUCCESS",
    FAVORITE_LOAD_FAIL: "FAVORITE_LOAD_FAIL",
    //语言标签
    LANGUAGE_LOAD_SUCCESS: "LANGUAGE_LOAD_SUCCESS",
    //搜索模块
    SEARCH_LOAD_MORE_SUCCESS: 'SEARCH_LOAD_MORE_SUCCESS',
    SEARCH_LOAD_MORE_FAIL: 'SEARCH_LOAD_MORE_FAIL',
    SEARCH_REFRESH: 'SEARCH_REFRESH',
    SEARCH_CANCEL: 'SEARCH_CANCEL',
    SEARCH_FAIL: 'SEARCH_FAIL',
    SEARCH_REFRESH_SUCCESS: 'SEARCH_REFRESH_SUCCESS',
}
