/**
 * @author HaganWu
 * @description types
 * @fileName types.js
 * @data 2021/10/25 14:42
 */
export default {
    //导航更换主题
    THEME_CHANGE: "THEME_CHANGE",
    THEME_INIT: "THEME_INIT",
    //最热页面
    POPULAR_REFRESH: "POPULAR_REFRESH",
    POPULAR_REFRESH_FAIL: "POPULAR_REFRESH_FAIL",
    POPULAR_REFRESH_SUCCESS: "POPULAR_REFRESH_SUCCESS",
    POPULAR_LOAD_MORE_SUCCESS: "POPULAR_LOAD_MORE_SUCCESS",
    POPULAR_LOAD_MORE_FAIL: "POPULAR_LOAD_MORE_FAIL",
    //趋势页面
    TRENDING_REFRESH: "TRENDING_REFRESH",
    TRENDING_REFRESH_FAIL: "TRENDING_REFRESH_FAIL",
    TRENDING_REFRESH_SUCCESS: "TRENDING_REFRESH_SUCCESS",
    TRENDING_LOAD_MORE_SUCCESS: "TRENDING_LOAD_MORE_SUCCESS",
    TRENDING_LOAD_MORE_FAIL: "TRENDING_LOAD_MORE_FAIL",
    //收藏页面
    FAVORITE_LOAD_DATA:"FAVORITE_LOAD_DATA",
    FAVORITE_LOAD_SUCCESS:"FAVORITE_LOAD_SUCCESS",
    FAVORITE_LOAD_FAIL:"FAVORITE_LOAD_FAIL",
}
